comment:
  layout: "files"
  behavior: default
  branches: null
  require_changes: no
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]

coverage:
  range: 20..100
  round: down
  precision: 2

  status:
    project:
      default:
        target: 30
        if_ci_failed: error
    patch: off
