FROM maven:3-openjdk-8

ENTRYPOINT ["/datadog-api-client-java/run-tests.sh"]

# Predownload the dependencies, so that execution of the image is fast.
# Also, this will make us better use Docker build cache, as pom.xml won't
# be changed very often and so maven dependency installation will be cached.
# Unfortunately there seems to be no way to download all scope:test
# dependencies, but at least this downloads most of them.
COPY pom.xml /tmp/mock-pom-structure/
RUN mvn --batch-mode -f /tmp/mock-pom-structure/pom.xml dependency:go-offline

COPY . /datadog-api-client-java

WORKDIR /datadog-api-client-java
