FROM fedora:30

RUN dnf install -y java-1.8.0-openjdk-headless maven && \
    dnf clean all

# Predownload the dependencies, so that execution of the image is fast.
# Also, this will make us better use Docker build cache, as pom.xml won't
# be changed very often and so maven dependency installation will be cached.
# Unfortunately there seems to be no way to download all scope:test
# dependencies, but at least this downloads most of them.
RUN mkdir -p /tmp/mock-pom-structure/v1
COPY pom.xml /tmp/mock-pom-structure/
COPY v1/pom.xml /tmp/mock-pom-structure/v1
RUN mvn --batch-mode -f /tmp/mock-pom-structure/v1/pom.xml dependency:go-offline

ENTRYPOINT ["mvn"]
CMD ["--batch-mode", "test"]

COPY . /tmp/datadog-api-client-java

WORKDIR /tmp/datadog-api-client-java
