/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.v2.client.model.RelationshipToOrganization;
import com.datadog.api.v2.client.model.RelationshipToOrganizations;
import com.datadog.api.v2.client.model.RelationshipToRoles;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Relationships of the role object returned by the API.
 */
@ApiModel(description = "Relationships of the role object returned by the API.")
@JsonPropertyOrder({
  RoleResponseRelationships.JSON_PROPERTY_ORG,
  RoleResponseRelationships.JSON_PROPERTY_OTHER_ORGS,
  RoleResponseRelationships.JSON_PROPERTY_OTHER_ROLES,
  RoleResponseRelationships.JSON_PROPERTY_ROLES
})

public class RoleResponseRelationships {
  public static final String JSON_PROPERTY_ORG = "org";
  private RelationshipToOrganization org;

  public static final String JSON_PROPERTY_OTHER_ORGS = "other_orgs";
  private RelationshipToOrganizations otherOrgs;

  public static final String JSON_PROPERTY_OTHER_ROLES = "other_roles";
  private RelationshipToRoles otherRoles;

  public static final String JSON_PROPERTY_ROLES = "roles";
  private RelationshipToRoles roles;


  public RoleResponseRelationships org(RelationshipToOrganization org) {
    
    this.org = org;
    return this;
  }

   /**
   * Get org
   * @return org
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipToOrganization getOrg() {
    return org;
  }


  public void setOrg(RelationshipToOrganization org) {
    this.org = org;
  }


  public RoleResponseRelationships otherOrgs(RelationshipToOrganizations otherOrgs) {
    
    this.otherOrgs = otherOrgs;
    return this;
  }

   /**
   * Get otherOrgs
   * @return otherOrgs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OTHER_ORGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipToOrganizations getOtherOrgs() {
    return otherOrgs;
  }


  public void setOtherOrgs(RelationshipToOrganizations otherOrgs) {
    this.otherOrgs = otherOrgs;
  }


  public RoleResponseRelationships otherRoles(RelationshipToRoles otherRoles) {
    
    this.otherRoles = otherRoles;
    return this;
  }

   /**
   * Get otherRoles
   * @return otherRoles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OTHER_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipToRoles getOtherRoles() {
    return otherRoles;
  }


  public void setOtherRoles(RelationshipToRoles otherRoles) {
    this.otherRoles = otherRoles;
  }


  public RoleResponseRelationships roles(RelationshipToRoles roles) {
    
    this.roles = roles;
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipToRoles getRoles() {
    return roles;
  }


  public void setRoles(RelationshipToRoles roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoleResponseRelationships roleResponseRelationships = (RoleResponseRelationships) o;
    return Objects.equals(this.org, roleResponseRelationships.org) &&
        Objects.equals(this.otherOrgs, roleResponseRelationships.otherOrgs) &&
        Objects.equals(this.otherRoles, roleResponseRelationships.otherRoles) &&
        Objects.equals(this.roles, roleResponseRelationships.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(org, otherOrgs, otherRoles, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoleResponseRelationships {\n");
    sb.append("    org: ").append(toIndentedString(org)).append("\n");
    sb.append("    otherOrgs: ").append(toIndentedString(otherOrgs)).append("\n");
    sb.append("    otherRoles: ").append(toIndentedString(otherRoles)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

