/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.datadog.api.v2.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Once a signal is generated, the signal will remain “open” if a case is matched at least once
 * within this keep alive window.
 */
public enum SecurityMonitoringRuleKeepAlive {
  ZERO_MINUTES(0),

  ONE_MINUTE(60),

  FIVE_MINUTES(300),

  TEN_MINUTES(600),

  FIFTEEN_MINUTES(900),

  THIRTY_MINUTES(1800),

  ONE_HOUR(3600),

  TWO_HOURS(7200),

  THREE_HOURS(10800),

  SIX_HOURS(21600);

  private Integer value;

  SecurityMonitoringRuleKeepAlive(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SecurityMonitoringRuleKeepAlive fromValue(Integer value) {
    for (SecurityMonitoringRuleKeepAlive b : SecurityMonitoringRuleKeepAlive.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
