/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v2.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.datadog.api.v2.client.model.ServiceRelationships;
import com.datadog.api.v2.client.model.ServiceType;
import com.datadog.api.v2.client.model.ServiceUpdateAttributes;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.datadog.api.v2.client.JSON;


/**
 * Service payload for update requests.
 */
@ApiModel(description = "Service payload for update requests.")
@JsonPropertyOrder({
  ServiceUpdateData.JSON_PROPERTY_ATTRIBUTES,
  ServiceUpdateData.JSON_PROPERTY_ID,
  ServiceUpdateData.JSON_PROPERTY_RELATIONSHIPS,
  ServiceUpdateData.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServiceUpdateData {
  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private ServiceUpdateAttributes attributes;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_RELATIONSHIPS = "relationships";
  private ServiceRelationships relationships;

  public static final String JSON_PROPERTY_TYPE = "type";
  private ServiceType type = ServiceType.SERVICES;


  public ServiceUpdateData attributes(ServiceUpdateAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServiceUpdateAttributes getAttributes() {
    return attributes;
  }


  public void setAttributes(ServiceUpdateAttributes attributes) {
    this.attributes = attributes;
  }


  public ServiceUpdateData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The service&#39;s ID.
   * @return id
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", required = true, value = "The service's ID.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ServiceUpdateData relationships(ServiceRelationships relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELATIONSHIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServiceRelationships getRelationships() {
    return relationships;
  }


  public void setRelationships(ServiceRelationships relationships) {
    this.relationships = relationships;
  }


  public ServiceUpdateData type(ServiceType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServiceType getType() {
    return type;
  }


  public void setType(ServiceType type) {
    this.type = type;
  }


  /**
   * Return true if this ServiceUpdateData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceUpdateData serviceUpdateData = (ServiceUpdateData) o;
    return Objects.equals(this.attributes, serviceUpdateData.attributes) &&
        Objects.equals(this.id, serviceUpdateData.id) &&
        Objects.equals(this.relationships, serviceUpdateData.relationships) &&
        Objects.equals(this.type, serviceUpdateData.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, id, relationships, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceUpdateData {\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

