/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

package com.datadog.api.client.v2.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * A composite rule combining several predicates. Used as an alternative to <code>nodes</code> on a
 * journey step when several conditions must be matched together, in any order or in a specific
 * order.
 */
@JsonPropertyOrder({
  RUMOperationJourneyCompositeRule.JSON_PROPERTY_COMPOSITE_RULE_ID,
  RUMOperationJourneyCompositeRule.JSON_PROPERTY_CONFIG_VERSION,
  RUMOperationJourneyCompositeRule.JSON_PROPERTY_KIND,
  RUMOperationJourneyCompositeRule.JSON_PROPERTY_MAX_WINDOW_MS,
  RUMOperationJourneyCompositeRule.JSON_PROPERTY_PREDICATES
})
@jakarta.annotation.Generated(
    value = "https://github.com/DataDog/datadog-api-client-java/blob/master/.generator")
public class RUMOperationJourneyCompositeRule {
  @JsonIgnore public boolean unparsed = false;
  public static final String JSON_PROPERTY_COMPOSITE_RULE_ID = "composite_rule_id";
  private String compositeRuleId;

  public static final String JSON_PROPERTY_CONFIG_VERSION = "config_version";
  private String configVersion;

  public static final String JSON_PROPERTY_KIND = "kind";
  private RUMOperationJourneyCompositeRuleKind kind;

  public static final String JSON_PROPERTY_MAX_WINDOW_MS = "max_window_ms";
  private Long maxWindowMs;

  public static final String JSON_PROPERTY_PREDICATES = "predicates";
  private List<RUMOperationJourneyPredicate> predicates = new ArrayList<>();

  public RUMOperationJourneyCompositeRule() {}

  @JsonCreator
  public RUMOperationJourneyCompositeRule(
      @JsonProperty(required = true, value = JSON_PROPERTY_KIND)
          RUMOperationJourneyCompositeRuleKind kind,
      @JsonProperty(required = true, value = JSON_PROPERTY_PREDICATES)
          List<RUMOperationJourneyPredicate> predicates) {
    this.kind = kind;
    this.unparsed |= !kind.isValid();
    this.predicates = predicates;
    for (RUMOperationJourneyPredicate item : predicates) {
      this.unparsed |= item.unparsed;
    }
  }

  /**
   * The unique identifier of the composite rule. Generated by the server if omitted.
   *
   * @return compositeRuleId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPOSITE_RULE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCompositeRuleId() {
    return compositeRuleId;
  }

  /**
   * A hash of the composite rule's configuration, computed by the server.
   *
   * @return configVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIG_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConfigVersion() {
    return configVersion;
  }

  public RUMOperationJourneyCompositeRule kind(RUMOperationJourneyCompositeRuleKind kind) {
    this.kind = kind;
    this.unparsed |= !kind.isValid();
    return this;
  }

  /**
   * The rule used to combine the composite rule's predicates. <code>all_of</code> requires every
   * predicate to match, in any order. <code>in_order</code> requires every predicate to match in
   * the given order.
   *
   * @return kind
   */
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RUMOperationJourneyCompositeRuleKind getKind() {
    return kind;
  }

  public void setKind(RUMOperationJourneyCompositeRuleKind kind) {
    if (!kind.isValid()) {
      this.unparsed = true;
    }
    this.kind = kind;
  }

  public RUMOperationJourneyCompositeRule maxWindowMs(Long maxWindowMs) {
    this.maxWindowMs = maxWindowMs;
    return this;
  }

  /**
   * The maximum time window, in milliseconds, in which all predicates must match.
   *
   * @return maxWindowMs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_WINDOW_MS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getMaxWindowMs() {
    return maxWindowMs;
  }

  public void setMaxWindowMs(Long maxWindowMs) {
    this.maxWindowMs = maxWindowMs;
  }

  public RUMOperationJourneyCompositeRule predicates(
      List<RUMOperationJourneyPredicate> predicates) {
    this.predicates = predicates;
    for (RUMOperationJourneyPredicate item : predicates) {
      this.unparsed |= item.unparsed;
    }
    return this;
  }

  public RUMOperationJourneyCompositeRule addPredicatesItem(
      RUMOperationJourneyPredicate predicatesItem) {
    this.predicates.add(predicatesItem);
    this.unparsed |= predicatesItem.unparsed;
    return this;
  }

  /**
   * The list of predicates that must be matched by RUM events.
   *
   * @return predicates
   */
  @JsonProperty(JSON_PROPERTY_PREDICATES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<RUMOperationJourneyPredicate> getPredicates() {
    return predicates;
  }

  public void setPredicates(List<RUMOperationJourneyPredicate> predicates) {
    this.predicates = predicates;
    if (predicates != null) {
      for (RUMOperationJourneyPredicate item : predicates) {
        this.unparsed |= item.unparsed;
      }
    }
  }

  /**
   * A container for additional, undeclared properties. This is a holder for any undeclared
   * properties as specified with the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value. If the property
   * does not already exist, create it otherwise replace it.
   *
   * @param key The arbitrary key to set
   * @param value The associated value
   * @return RUMOperationJourneyCompositeRule
   */
  @JsonAnySetter
  public RUMOperationJourneyCompositeRule putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return The additional properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key The arbitrary key to get
   * @return The specific additional property for the given key
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
      return null;
    }
    return this.additionalProperties.get(key);
  }

  /** Return true if this RUMOperationJourneyCompositeRule object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RUMOperationJourneyCompositeRule rumOperationJourneyCompositeRule =
        (RUMOperationJourneyCompositeRule) o;
    return Objects.equals(this.compositeRuleId, rumOperationJourneyCompositeRule.compositeRuleId)
        && Objects.equals(this.configVersion, rumOperationJourneyCompositeRule.configVersion)
        && Objects.equals(this.kind, rumOperationJourneyCompositeRule.kind)
        && Objects.equals(this.maxWindowMs, rumOperationJourneyCompositeRule.maxWindowMs)
        && Objects.equals(this.predicates, rumOperationJourneyCompositeRule.predicates)
        && Objects.equals(
            this.additionalProperties, rumOperationJourneyCompositeRule.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        compositeRuleId, configVersion, kind, maxWindowMs, predicates, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RUMOperationJourneyCompositeRule {\n");
    sb.append("    compositeRuleId: ").append(toIndentedString(compositeRuleId)).append("\n");
    sb.append("    configVersion: ").append(toIndentedString(configVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    maxWindowMs: ").append(toIndentedString(maxWindowMs)).append("\n");
    sb.append("    predicates: ").append(toIndentedString(predicates)).append("\n");
    sb.append("    additionalProperties: ")
        .append(toIndentedString(additionalProperties))
        .append("\n");
    sb.append('}');
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
