/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.api;

import com.datadog.api.v1.client.ApiException;
import com.datadog.api.v1.client.model.DashboardList;
import com.datadog.api.v1.client.model.DashboardListDeleteResponse;
import static org.junit.Assert.*;

import org.junit.*;

import java.util.ArrayList;

/**
 * API tests for DashboardListsApi
 */
@Ignore
public class DashboardListsApiTest extends V1ApiTest {

    private static DashboardListsApi api;
    private ArrayList<Long> dashboardListsToDelete;

    @Before
    public void resetDeleteDowntimes() {
        dashboardListsToDelete = new ArrayList<Long>();
    }

    @BeforeClass
    public static void initApi() {
        api = new DashboardListsApi(generalApiClient);
    }

    @Test
    public void dashboardListCreateModifyDeleteTest() throws ApiException {

        long start = System.currentTimeMillis();
        DashboardList testDashboardList = new DashboardList().name(String.format("dash %d", start));

        // Create dashboard list
        DashboardList dashboardList = api.createDashboardList(testDashboardList).execute();
        dashboardListsToDelete.add(dashboardList.getId());
        assertEquals(dashboardList.getName(), testDashboardList.getName());

        // Get the dashboard list
        dashboardList = api.getDashboardList(dashboardList.getId()).execute();
        assertEquals(dashboardList.getName(), testDashboardList.getName());

        // Edit the dashboard list
        DashboardList editedDashboardList = new DashboardList().name(String.format("updated dash %d", start));
        dashboardList = api.updateDashboardList(dashboardList.getId(), editedDashboardList).execute();
        assertEquals(dashboardList.getName(), editedDashboardList.getName());

        // Delete the dashboard list
        DashboardListDeleteResponse res = api.deleteDashboardList(dashboardList.getId()).execute();
        assertEquals(res.getDeletedDashboardListId(), dashboardList.getId());
    }

    @After
    public void deleteDashboardLists() throws ApiException {
        if (dashboardListsToDelete != null) {
            for (Long id : dashboardListsToDelete) {
                try {
                    api.getDashboardList(id).execute();
                } catch (ApiException e) {
                    // doesn't exist => continue
                    continue;
                }
                api.deleteDashboardList(id).execute();
            }
        }
    }
}
