/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.DashboardList;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DashboardListListResponse
 */
public class DashboardListListResponseTest {
    private final DashboardListListResponse model = new DashboardListListResponse();

    /**
     * Model tests for DashboardListListResponse
     */
    @Test
    public void testDashboardListListResponse() {
        // TODO: test DashboardListListResponse
    }

    /**
     * Test the property 'dashboardLists'
     */
    @Test
    public void dashboardListsTest() {
        // TODO: test dashboardLists
    }

}
