/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.FormulaAndFunctionEventAggregation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FormulaAndFunctionEventQueryDefinitionCompute
 */
public class FormulaAndFunctionEventQueryDefinitionComputeTest {
    private final FormulaAndFunctionEventQueryDefinitionCompute model = new FormulaAndFunctionEventQueryDefinitionCompute();

    /**
     * Model tests for FormulaAndFunctionEventQueryDefinitionCompute
     */
    @Test
    public void testFormulaAndFunctionEventQueryDefinitionCompute() {
        // TODO: test FormulaAndFunctionEventQueryDefinitionCompute
    }

    /**
     * Test the property 'aggregation'
     */
    @Test
    public void aggregationTest() {
        // TODO: test aggregation
    }

    /**
     * Test the property 'interval'
     */
    @Test
    public void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'metric'
     */
    @Test
    public void metricTest() {
        // TODO: test metric
    }

}
