/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.EventQueryDefinition;
import com.datadog.api.v1.client.model.LogQueryDefinition;
import com.datadog.api.v1.client.model.ProcessQueryDefinition;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HostMapRequest
 */
public class HostMapRequestTest {
    private final HostMapRequest model = new HostMapRequest();

    /**
     * Model tests for HostMapRequest
     */
    @Test
    public void testHostMapRequest() {
        // TODO: test HostMapRequest
    }

    /**
     * Test the property 'apmQuery'
     */
    @Test
    public void apmQueryTest() {
        // TODO: test apmQuery
    }

    /**
     * Test the property 'eventQuery'
     */
    @Test
    public void eventQueryTest() {
        // TODO: test eventQuery
    }

    /**
     * Test the property 'logQuery'
     */
    @Test
    public void logQueryTest() {
        // TODO: test logQuery
    }

    /**
     * Test the property 'networkQuery'
     */
    @Test
    public void networkQueryTest() {
        // TODO: test networkQuery
    }

    /**
     * Test the property 'processQuery'
     */
    @Test
    public void processQueryTest() {
        // TODO: test processQuery
    }

    /**
     * Test the property 'q'
     */
    @Test
    public void qTest() {
        // TODO: test q
    }

    /**
     * Test the property 'rumQuery'
     */
    @Test
    public void rumQueryTest() {
        // TODO: test rumQuery
    }

}
