/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.SyntheticsSSLCertificateIssuer;
import com.datadog.api.v1.client.model.SyntheticsSSLCertificateSubject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SyntheticsSSLCertificate
 */
public class SyntheticsSSLCertificateTest {
    private final SyntheticsSSLCertificate model = new SyntheticsSSLCertificate();

    /**
     * Model tests for SyntheticsSSLCertificate
     */
    @Test
    public void testSyntheticsSSLCertificate() {
        // TODO: test SyntheticsSSLCertificate
    }

    /**
     * Test the property 'cipher'
     */
    @Test
    public void cipherTest() {
        // TODO: test cipher
    }

    /**
     * Test the property 'exponent'
     */
    @Test
    public void exponentTest() {
        // TODO: test exponent
    }

    /**
     * Test the property 'extKeyUsage'
     */
    @Test
    public void extKeyUsageTest() {
        // TODO: test extKeyUsage
    }

    /**
     * Test the property 'fingerprint'
     */
    @Test
    public void fingerprintTest() {
        // TODO: test fingerprint
    }

    /**
     * Test the property 'fingerprint256'
     */
    @Test
    public void fingerprint256Test() {
        // TODO: test fingerprint256
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'modulus'
     */
    @Test
    public void modulusTest() {
        // TODO: test modulus
    }

    /**
     * Test the property 'protocol'
     */
    @Test
    public void protocolTest() {
        // TODO: test protocol
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'validFrom'
     */
    @Test
    public void validFromTest() {
        // TODO: test validFrom
    }

    /**
     * Test the property 'validTo'
     */
    @Test
    public void validToTest() {
        // TODO: test validTo
    }

}
