/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.GeomapWidgetDefinitionStyle;
import com.datadog.api.v1.client.model.GeomapWidgetDefinitionType;
import com.datadog.api.v1.client.model.GeomapWidgetDefinitionView;
import com.datadog.api.v1.client.model.GeomapWidgetRequest;
import com.datadog.api.v1.client.model.WidgetCustomLink;
import com.datadog.api.v1.client.model.WidgetTextAlign;
import com.datadog.api.v1.client.model.WidgetTime;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GeomapWidgetDefinition
 */
public class GeomapWidgetDefinitionTest {
    private final GeomapWidgetDefinition model = new GeomapWidgetDefinition();

    /**
     * Model tests for GeomapWidgetDefinition
     */
    @Test
    public void testGeomapWidgetDefinition() {
        // TODO: test GeomapWidgetDefinition
    }

    /**
     * Test the property 'customLinks'
     */
    @Test
    public void customLinksTest() {
        // TODO: test customLinks
    }

    /**
     * Test the property 'requests'
     */
    @Test
    public void requestsTest() {
        // TODO: test requests
    }

    /**
     * Test the property 'style'
     */
    @Test
    public void styleTest() {
        // TODO: test style
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'titleAlign'
     */
    @Test
    public void titleAlignTest() {
        // TODO: test titleAlign
    }

    /**
     * Test the property 'titleSize'
     */
    @Test
    public void titleSizeTest() {
        // TODO: test titleSize
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'view'
     */
    @Test
    public void viewTest() {
        // TODO: test view
    }

}
