/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import com.datadog.api.v1.client.model.HostMapRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HostMapWidgetDefinitionRequests
 */
public class HostMapWidgetDefinitionRequestsTest {
    private final HostMapWidgetDefinitionRequests model = new HostMapWidgetDefinitionRequests();

    /**
     * Model tests for HostMapWidgetDefinitionRequests
     */
    @Test
    public void testHostMapWidgetDefinitionRequests() {
        // TODO: test HostMapWidgetDefinitionRequests
    }

    /**
     * Test the property 'fill'
     */
    @Test
    public void fillTest() {
        // TODO: test fill
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

}
