/*
 * (C) Datadog, Inc. 2019
 * All rights reserved
 * Licensed under a 3-clause BSD style license (see LICENSE)
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.v1.client.model.HistoryServiceLevelObjectiveMetricsSeriesMetadata;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A representation of &#x60;metric&#x60; based SLO time series for the provided queries. This is the same response type from &#x60;batch_query&#x60; endpoint.
 */
@ApiModel(description = "A representation of `metric` based SLO time series for the provided queries. This is the same response type from `batch_query` endpoint.")
@JsonPropertyOrder({
  HistoryServiceLevelObjectiveMetricsSeries.JSON_PROPERTY_COUNT,
  HistoryServiceLevelObjectiveMetricsSeries.JSON_PROPERTY_METADATA,
  HistoryServiceLevelObjectiveMetricsSeries.JSON_PROPERTY_SUM,
  HistoryServiceLevelObjectiveMetricsSeries.JSON_PROPERTY_TIMES,
  HistoryServiceLevelObjectiveMetricsSeries.JSON_PROPERTY_VALUES
})

public class HistoryServiceLevelObjectiveMetricsSeries {
  public static final String JSON_PROPERTY_COUNT = "count";
  private Long count;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private HistoryServiceLevelObjectiveMetricsSeriesMetadata metadata;

  public static final String JSON_PROPERTY_SUM = "sum";
  private Double sum;

  public static final String JSON_PROPERTY_TIMES = "times";
  private List<Long> times = null;

  public static final String JSON_PROPERTY_VALUES = "values";
  private List<BigDecimal> values = null;


  public HistoryServiceLevelObjectiveMetricsSeries count(Long count) {
    
    this.count = count;
    return this;
  }

   /**
   * Count of submitted metrics
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of submitted metrics")
  @JsonProperty(JSON_PROPERTY_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCount() {
    return count;
  }


  public void setCount(Long count) {
    this.count = count;
  }


  public HistoryServiceLevelObjectiveMetricsSeries metadata(HistoryServiceLevelObjectiveMetricsSeriesMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HistoryServiceLevelObjectiveMetricsSeriesMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(HistoryServiceLevelObjectiveMetricsSeriesMetadata metadata) {
    this.metadata = metadata;
  }


  public HistoryServiceLevelObjectiveMetricsSeries sum(Double sum) {
    
    this.sum = sum;
    return this;
  }

   /**
   * Total Sum of the query
   * @return sum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total Sum of the query")
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSum() {
    return sum;
  }


  public void setSum(Double sum) {
    this.sum = sum;
  }


  public HistoryServiceLevelObjectiveMetricsSeries times(List<Long> times) {
    
    this.times = times;
    return this;
  }

  public HistoryServiceLevelObjectiveMetricsSeries addTimesItem(Long timesItem) {
    if (this.times == null) {
      this.times = new ArrayList<Long>();
    }
    this.times.add(timesItem);
    return this;
  }

   /**
   * The query timestamps in epoch seconds
   * @return times
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The query timestamps in epoch seconds")
  @JsonProperty(JSON_PROPERTY_TIMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getTimes() {
    return times;
  }


  public void setTimes(List<Long> times) {
    this.times = times;
  }


  public HistoryServiceLevelObjectiveMetricsSeries values(List<BigDecimal> values) {
    
    this.values = values;
    return this;
  }

  public HistoryServiceLevelObjectiveMetricsSeries addValuesItem(BigDecimal valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<BigDecimal>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The query values
   * @return values
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The query values")
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BigDecimal> getValues() {
    return values;
  }


  public void setValues(List<BigDecimal> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryServiceLevelObjectiveMetricsSeries historyServiceLevelObjectiveMetricsSeries = (HistoryServiceLevelObjectiveMetricsSeries) o;
    return Objects.equals(this.count, historyServiceLevelObjectiveMetricsSeries.count) &&
        Objects.equals(this.metadata, historyServiceLevelObjectiveMetricsSeries.metadata) &&
        Objects.equals(this.sum, historyServiceLevelObjectiveMetricsSeries.sum) &&
        Objects.equals(this.times, historyServiceLevelObjectiveMetricsSeries.times) &&
        Objects.equals(this.values, historyServiceLevelObjectiveMetricsSeries.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, metadata, sum, times, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryServiceLevelObjectiveMetricsSeries {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    times: ").append(toIndentedString(times)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

