/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * HostMetrics
 */
@JsonPropertyOrder({
  HostMetrics.JSON_PROPERTY_CPU,
  HostMetrics.JSON_PROPERTY_IOWAIT,
  HostMetrics.JSON_PROPERTY_LOAD
})

public class HostMetrics {
  public static final String JSON_PROPERTY_CPU = "cpu";
  private Double cpu;

  public static final String JSON_PROPERTY_IOWAIT = "iowait";
  private Double iowait;

  public static final String JSON_PROPERTY_LOAD = "load";
  private Double load;


  public HostMetrics cpu(Double cpu) {
    
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "99.0", value = "")
  @JsonProperty(JSON_PROPERTY_CPU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCpu() {
    return cpu;
  }


  public void setCpu(Double cpu) {
    this.cpu = cpu;
  }


  public HostMetrics iowait(Double iowait) {
    
    this.iowait = iowait;
    return this;
  }

   /**
   * Get iowait
   * @return iowait
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3.2", value = "")
  @JsonProperty(JSON_PROPERTY_IOWAIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getIowait() {
    return iowait;
  }


  public void setIowait(Double iowait) {
    this.iowait = iowait;
  }


  public HostMetrics load(Double load) {
    
    this.load = load;
    return this;
  }

   /**
   * Get load
   * @return load
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.5", value = "")
  @JsonProperty(JSON_PROPERTY_LOAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLoad() {
    return load;
  }


  public void setLoad(Double load) {
    this.load = load;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HostMetrics hostMetrics = (HostMetrics) o;
    return Objects.equals(this.cpu, hostMetrics.cpu) &&
        Objects.equals(this.iowait, hostMetrics.iowait) &&
        Objects.equals(this.load, hostMetrics.load);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpu, iowait, load);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HostMetrics {\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    iowait: ").append(toIndentedString(iowait)).append("\n");
    sb.append("    load: ").append(toIndentedString(load)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

