/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.datadog.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** A list of SLO correction objects */
@ApiModel(description = "A list of  SLO correction objects")
@JsonPropertyOrder({SLOCorrectionListResponse.JSON_PROPERTY_DATA})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SLOCorrectionListResponse {
  public static final String JSON_PROPERTY_DATA = "data";
  private List<SLOCorrection> data = null;

  public SLOCorrectionListResponse data(List<SLOCorrection> data) {
    this.data = data;
    return this;
  }

  public SLOCorrectionListResponse addDataItem(SLOCorrection dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * The list of of SLO corrections objects
   *
   * @return data
   */
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of of SLO corrections objects")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SLOCorrection> getData() {
    return data;
  }

  public void setData(List<SLOCorrection> data) {
    this.data = data;
  }

  /** Return true if this SLOCorrectionListResponse object is equal to o. */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SLOCorrectionListResponse slOCorrectionListResponse = (SLOCorrectionListResponse) o;
    return Objects.equals(this.data, slOCorrectionListResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SLOCorrectionListResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
