/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TODO.
 */
@ApiModel(description = "TODO.")
@JsonPropertyOrder({
  SyntheticsGetTestLatestResultsPayload.JSON_PROPERTY_FROM_TS,
  SyntheticsGetTestLatestResultsPayload.JSON_PROPERTY_PROBE_DC,
  SyntheticsGetTestLatestResultsPayload.JSON_PROPERTY_TO_TS
})

public class SyntheticsGetTestLatestResultsPayload {
  public static final String JSON_PROPERTY_FROM_TS = "from_ts";
  private Double fromTs;

  public static final String JSON_PROPERTY_PROBE_DC = "probe_dc";
  private List<String> probeDc = null;

  public static final String JSON_PROPERTY_TO_TS = "to_ts";
  private Double toTs;


  public SyntheticsGetTestLatestResultsPayload fromTs(Double fromTs) {
    
    this.fromTs = fromTs;
    return this;
  }

   /**
   * TODO.
   * @return fromTs
  **/
  @ApiModelProperty(required = true, value = "TODO.")
  @JsonProperty(JSON_PROPERTY_FROM_TS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFromTs() {
    return fromTs;
  }


  public void setFromTs(Double fromTs) {
    this.fromTs = fromTs;
  }


  public SyntheticsGetTestLatestResultsPayload probeDc(List<String> probeDc) {
    
    this.probeDc = probeDc;
    return this;
  }

  public SyntheticsGetTestLatestResultsPayload addProbeDcItem(String probeDcItem) {
    if (this.probeDc == null) {
      this.probeDc = new ArrayList<>();
    }
    this.probeDc.add(probeDcItem);
    return this;
  }

   /**
   * TODO.
   * @return probeDc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TODO.")
  @JsonProperty(JSON_PROPERTY_PROBE_DC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getProbeDc() {
    return probeDc;
  }


  public void setProbeDc(List<String> probeDc) {
    this.probeDc = probeDc;
  }


  public SyntheticsGetTestLatestResultsPayload toTs(Double toTs) {
    
    this.toTs = toTs;
    return this;
  }

   /**
   * TODO.
   * @return toTs
  **/
  @ApiModelProperty(required = true, value = "TODO.")
  @JsonProperty(JSON_PROPERTY_TO_TS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getToTs() {
    return toTs;
  }


  public void setToTs(Double toTs) {
    this.toTs = toTs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyntheticsGetTestLatestResultsPayload syntheticsGetTestLatestResultsPayload = (SyntheticsGetTestLatestResultsPayload) o;
    return Objects.equals(this.fromTs, syntheticsGetTestLatestResultsPayload.fromTs) &&
        Objects.equals(this.probeDc, syntheticsGetTestLatestResultsPayload.probeDc) &&
        Objects.equals(this.toTs, syntheticsGetTestLatestResultsPayload.toTs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromTs, probeDc, toTs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyntheticsGetTestLatestResultsPayload {\n");
    sb.append("    fromTs: ").append(toIndentedString(fromTs)).append("\n");
    sb.append("    probeDc: ").append(toIndentedString(probeDc)).append("\n");
    sb.append("    toTs: ").append(toIndentedString(toTs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

