/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v1.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.datadog.api.v1.client.model.SyntheticsResourceType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Object describing a resource which is the combination of requests (fetch, xhr) and Assets (HTML, CSS, JS, images).
 */
@ApiModel(description = "Object describing a resource which is the combination of requests (fetch, xhr) and Assets (HTML, CSS, JS, images).")
@JsonPropertyOrder({
  SyntheticsResource.JSON_PROPERTY_DURATION,
  SyntheticsResource.JSON_PROPERTY_METHOD,
  SyntheticsResource.JSON_PROPERTY_SIZE,
  SyntheticsResource.JSON_PROPERTY_STATUS,
  SyntheticsResource.JSON_PROPERTY_TIMESTAMP,
  SyntheticsResource.JSON_PROPERTY_TRACE_ID,
  SyntheticsResource.JSON_PROPERTY_TYPE,
  SyntheticsResource.JSON_PROPERTY_URL
})

public class SyntheticsResource {
  public static final String JSON_PROPERTY_DURATION = "duration";
  private Double duration;

  public static final String JSON_PROPERTY_METHOD = "method";
  private String method;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Long size;

  public static final String JSON_PROPERTY_STATUS = "status";
  private Long status;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Double timestamp;

  public static final String JSON_PROPERTY_TRACE_ID = "traceId";
  private String traceId;

  public static final String JSON_PROPERTY_TYPE = "type";
  private SyntheticsResourceType type;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;


  public SyntheticsResource duration(Double duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Number of time the resource was collected.
   * @return duration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of time the resource was collected.")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getDuration() {
    return duration;
  }


  public void setDuration(Double duration) {
    this.duration = duration;
  }


  public SyntheticsResource method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * HTTP methode associated to the resource.
   * @return method
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "HTTP methode associated to the resource.")
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMethod() {
    return method;
  }


  public void setMethod(String method) {
    this.method = method;
  }


  public SyntheticsResource size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * Size of the resource in bytes.
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Size of the resource in bytes.")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  public void setSize(Long size) {
    this.size = size;
  }


  public SyntheticsResource status(Long status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status Code of the resource.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status Code of the resource.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStatus() {
    return status;
  }


  public void setStatus(Long status) {
    this.status = status;
  }


  public SyntheticsResource timestamp(Double timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp of the resource collection.
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timestamp of the resource collection.")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Double timestamp) {
    this.timestamp = timestamp;
  }


  public SyntheticsResource traceId(String traceId) {
    
    this.traceId = traceId;
    return this;
  }

   /**
   * Trace ID associated with the resource if any.
   * @return traceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Trace ID associated with the resource if any.")
  @JsonProperty(JSON_PROPERTY_TRACE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTraceId() {
    return traceId;
  }


  public void setTraceId(String traceId) {
    this.traceId = traceId;
  }


  public SyntheticsResource type(SyntheticsResourceType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SyntheticsResourceType getType() {
    return type;
  }


  public void setType(SyntheticsResourceType type) {
    this.type = type;
  }


  public SyntheticsResource url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL of the resource.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL of the resource.")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyntheticsResource syntheticsResource = (SyntheticsResource) o;
    return Objects.equals(this.duration, syntheticsResource.duration) &&
        Objects.equals(this.method, syntheticsResource.method) &&
        Objects.equals(this.size, syntheticsResource.size) &&
        Objects.equals(this.status, syntheticsResource.status) &&
        Objects.equals(this.timestamp, syntheticsResource.timestamp) &&
        Objects.equals(this.traceId, syntheticsResource.traceId) &&
        Objects.equals(this.type, syntheticsResource.type) &&
        Objects.equals(this.url, syntheticsResource.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, method, size, status, timestamp, traceId, type, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyntheticsResource {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

