/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.datadog.api.v1.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Navigate between different tabs for your browser test. */
public enum SyntheticsPlayingTab {
  MAIN_TAB(-1l),

  NEW_TAB(0l),

  TAB_1(1l),

  TAB_2(2l),

  TAB_3(3l);

  private Long value;

  SyntheticsPlayingTab(Long value) {
    this.value = value;
  }

  @JsonValue
  public Long getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SyntheticsPlayingTab fromValue(Long value) {
    for (SyntheticsPlayingTab b : SyntheticsPlayingTab.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
