/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v2.client.api;

import com.datadog.api.v2.client.*;
import com.datadog.api.v2.client.auth.*;
import com.datadog.api.v2.client.model.APIErrorResponse;
import com.datadog.api.v2.client.model.TeamCreateRequest;
import com.datadog.api.v2.client.model.TeamResponse;
import com.datadog.api.v2.client.model.TeamUpdateRequest;
import com.datadog.api.v2.client.model.TeamsResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeamsApi
 */
public class TeamsApiTest {

    private final TeamsApi api = new TeamsApi();

    /**
     * Create a new team
     *
     * Creates a new team.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTeamTest() throws ApiException {
        //TeamCreateRequest body = null;
        //TeamResponse response = api.createTeam()
        //        .body(body)
        //        .execute();
        // TODO: test validations
    }

    /**
     * Delete an existing team
     *
     * Deletes an existing team.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTeamTest() throws ApiException {
        //String teamId = null;
        //api.deleteTeam(teamId)
        //        .execute();
        // TODO: test validations
    }

    /**
     * Get details of a team
     *
     * Get details of a team. If the &#x60;include[users]&#x60; query parameter is provided, the included attribute will contain the users related to these teams.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeamTest() throws ApiException {
        //String teamId = null;
        //String include = null;
        //TeamResponse response = api.getTeam(teamId)
        //        .include(include)
        //        .execute();
        // TODO: test validations
    }

    /**
     * Get a list of all teams
     *
     * Get all teams for the requesting user&#39;s organization. If the &#x60;include[users]&#x60; query parameter is provided, the included attribute will contain the users related to these teams.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTeamsTest() throws ApiException {
        //String include = null;
        //Long pageSize = null;
        //Long pageOffset = null;
        //TeamsResponse response = api.getTeams()
        //        .include(include)
        //        .pageSize(pageSize)
        //        .pageOffset(pageOffset)
        //        .execute();
        // TODO: test validations
    }

    /**
     * Update an existing team
     *
     * Updates an existing team. Only provide the attributes which should be updated as this request is a partial update.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTeamTest() throws ApiException {
        //String teamId = null;
        //TeamUpdateRequest body = null;
        //TeamResponse response = api.updateTeam(teamId)
        //        .body(body)
        //        .execute();
        // TODO: test validations
    }

}
