# Trust policy for pre-commit fixes on pull requests
# Allows pushing pre-commit fixes back to PR branches
# Will be called in reusable-pre-commit.yml
issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/datadog-api-client-java:pull_request

claim_pattern:
  event_name: pull_request
  # Even when running pull_request, the workflow code comes from the base branch, hence refs/heads/master
  job_workflow_ref: DataDog/datadog-api-client-java/\.github/workflows/reusable-pre-commit\.yml@refs/heads/master
  repository: DataDog/datadog-api-client-java
  ref: refs/heads/master

permissions:
  contents: write # Required for pushing pre-commit fixes
