name: Prepare Release

on:
  push:
    branches:
      - master

jobs:
  prep-release:
   # Use ubuntu-18.04 image so we have Java 8 + Maven 3 - https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
   # We only need to use the `mvn release:prepare` command here to perform the SCM actions, the full build and release happens in .gitlab-ci.yml
   runs-on: ubuntu-18.04
   if: contains(github.event.head_commit.message, '[trigger release]')
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Configure Git user
     run: |
       git config user.email "package@datadoghq.com"
       git config user.name "Datadog"
   - name: Prepare repo for release
     run: mvn -B -DskipTests -Darguments=-DskipTests release:prepare
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
