name: Reusable Javadoc Workflow

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Branch to checkout and test (defaults to the calling branch)'
        required: false
        type: string
        default: ''
      java-version:
        description: 'Java version to use for javadoc'
        required: false
        type: string
        default: '8'

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: DataDog/datadog-api-client-java
          ref: ${{ inputs.target-branch || github.ref }}
      - name: Install Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
          cache: "maven"
      - name: Build javadoc
        run: mvn javadoc:javadoc
        shell: bash