/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.datadog.api.v2.client.model;

import com.datadog.api.v2.client.model.IncidentServicesResponseMeta;
import com.datadog.api.v2.client.model.IncidentTeamIncludedItems;
import com.datadog.api.v2.client.model.IncidentTeamResponseData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IncidentTeamsResponse
 */
public class IncidentTeamsResponseTest {
    private final IncidentTeamsResponse model = new IncidentTeamsResponse();

    /**
     * Model tests for IncidentTeamsResponse
     */
    @Test
    public void testIncidentTeamsResponse() {
        // TODO: test IncidentTeamsResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'included'
     */
    @Test
    public void includedTest() {
        // TODO: test included
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
